export const sv = {
  menu: {
    tournament: 'Turnering',
    newTournament: 'Ny',
    editTournament: 'Editera',
    deleteTournament: 'Ta bort',
    pairing: 'Lotta',
    pairNextRound: 'Lotta nästa rond',
    unpairLastRound: 'Ångra lottning',
    addBoard: 'Lägg till bord',
    editBoard: 'Editera bord',
    deleteBoard: 'Ta bort bord',
    standings: 'Ställning',
    players: 'Spelare',
    playerPool: 'Spelarpool',
    tournamentPlayers: 'Turneringsspelare',
    settings: 'Inställningar',
    backupDatabase: 'Säkerhetskopiera databas',
    restoreDatabase: 'Återställ databas',
    print: 'Skriv ut',
    printPairing: 'Skriv ut lottning',
    printStandings: 'Skriv ut ställning',
    printPlayerList: 'Skriv ut spelarlista',
    printAlphabetical: 'Skriv ut alfabetisk lottning',
    printClubStandings: 'Skriv ut klubbställning',
    publish: 'Publicera',
    publishPairing: 'Publicera lottning',
    publishStandings: 'Publicera ställning',
    publishPlayerList: 'Publicera spelarlista',
    publishRounds: 'Publicera korstabell',
    publishClubStandings: 'Publicera klubbställning',
    publishAlphabetical: 'Publicera alfabetisk lottning',
    printChess4Standings: 'Skriv ut Schack4an-ställning',
    publishChess4Standings: 'Publicera Schack4an-ställning',
    export: 'Exportera',
    exportPlayers: 'Exportera spelare',
    exportLiveChess: 'Exportera till LiveChess',
    import: 'Importera',
    importPlayers: 'Importera spelare',
  },
  tabs: {
    pairings: 'Lottning & resultat',
    alphabetical: 'Alfabetisk lottning',
    standings: 'Ställning',
    players: 'Spelare',
    clubStandings: 'Klubbställning',
    chess4Setup: 'Schack4an inställningar klasstorlek',
    chess4Standings: 'Schack4an ställning',
    live: 'Live (Beta)',
  },
  columns: {
    board: 'Bord',
    whitePlayer: 'Vit spelare',
    rating: 'Rating',
    result: 'Resultat',
    blackPlayer: 'Svart spelare',
    place: 'Plac',
    name: 'Namn',
    club: 'Klubb',
    group: 'Grupp',
    score: 'Poäng',
    players: 'Spelare',
    klass: 'Klass',
    teamSize: 'Klasstorlek',
  },
  contextMenu: {
    notPlayed: 'Ej spelad',
    whiteWin: 'Vit vinst',
    draw: 'Remi',
    blackWin: 'Svart vinst',
    walkOver: 'Walk over',
    whiteWinWO: 'Vit vinst',
    blackWinWO: 'Svart vinst',
    doubleWO: 'Dubbel wo',
    postponed: 'Uppskjuten',
    cancelled: 'Inställd',
    editScore: 'Editera poäng',
  },
  selector: {
    tournament: 'Turnering:',
    group: 'Grupp:',
    round: 'Rond:',
    activeTournament: 'Aktiv turnering',
  },
  status: {
    notStarted: 'Ej startad',
    tournament: 'Turnering',
    group: 'Grupp',
    round: 'Rond',
  },
  common: {
    save: 'Spara',
    cancel: 'Avbryt',
    delete: 'Ta bort',
    add: 'Lägg till',
    addToTournament: 'Lägg till i turneringen',
    change: 'Ändra',
    close: 'Stäng',
    yes: 'Ja',
    no: 'Nej',
    ok: 'OK',
    confirm: 'Bekräfta',
    noTournament: 'Ingen turnering vald',
    noRoundPaired: 'Ingen rond lottad',
    noGamesInRound: 'Inga partier i denna rond',
    noStandings: 'Ingen ställning',
    noPlayers: 'Inga spelare',
    noRounds: 'Inga ronder',
    noClubStandings: 'Ingen klubbställning',
    noClubs: 'Inga klubbar',
    noChess4Standings: 'Ingen Schack4an-ställning',
  },
  guidance: {
    step1Path: 'Turnering \u2192 Ny',
    step1Label: 'Skapa en ny turnering',
    step2Path: 'Spelare \u2192 Spelarpool',
    step2Label: 'Lägg till spelare',
    step3Path: 'Lotta \u2192 Lotta nästa rond',
    step3Label: 'Starta lottningen',
  },
  tournament: {
    name: 'Turneringsnamn',
    pairingSystem: 'Lottningssystem',
    initialPairing: 'Initial spelarordning',
    nrOfRounds: 'Antal ronder',
    pointsPerGame: 'Poäng per match',
    barredPairing: 'Låt ej spelare från samma klubb mötas',
    compensateWeak: 'Räkna uppskjutna partier som remi för den svagare',
    chess4: 'Detta är en schack4an-tävling',
    showELO: 'Visa rating',
    showGroup: 'Visa Gruppkolumn',
    ratingChoice: 'Vid schweizerlottning: Lotta med avseende på',
    tiebreaks: 'Särskilning',
    availableTiebreaks: 'Valbara',
    selectedTiebreaks: 'Valda',
    webPublishing: 'Webbpublicering',
    resultsPage: 'Lottning',
    standingsPage: 'Ställning',
    playerListPage: 'Spelarlista',
    roundForRoundPage: 'Korstabell',
    clubStandingsPage: 'Klubbställning',
    roundDates: 'Ronddatum',
    deputyArbiter: 'Biträdande domare',
    nameAndGroupRequired: 'Vänligen ange turneringsnamn och grupp.',
  },
  player: {
    firstName: 'Förnamn',
    lastName: 'Efternamn',
    club: 'Klubb',
    title: 'Titel',
    sex: 'Kön',
    federation: 'Federation',
    fideId: 'FIDE id',
    ssfId: 'SSF id',
    birthdate: 'Födelsedag (YYYY-MM-DD)',
    withdrawn: 'Utgå från rond',
    fromRound: 'Från rond',
    manualTiebreak: 'Manuell särskiljning',
    tiebreakValue: 'Värde',
    tournamentSettings: 'Spelarinställningar i turneringen',
    editTournamentPlayersTitle: 'Editera turneringsspelare i turnering',
    playersRegistered: 'spelare registrerade i turneringen.',
    playersInPool: 'spelare i poolen.',
    createOrEdit: 'Skapa eller editera spelare',
    fideInformation: 'FIDE-information',
    ratingELO: 'Rating ELO',
    rapidELO: 'Snabb-ELO',
    blitzELO: 'Blixt-ELO',
    kFactor: 'K-faktor',
    nameRequired: 'Spelare måste ha förnamn eller efternamn.',
    reset: 'Rensa formulär (ny spelarinmatning)',
    mainTab: 'Allmänt',
    fideTab: 'FIDE',
    otherTab: 'Övrigt',
    updateData: 'Uppdatera uppgifter',
    poolNote:
      'Not: Spelare från spelarpoolen KOPIERAS in i turneringen. Det betyder att editera en turneringsspelare påverkar inte spelaren i spelarpoolen.',
    editPoolTitle: 'Ändra i spelarpool',
    discardChangesTitle: 'Osparade ändringar',
    discardChangesMessage:
      'Du har osparade ändringar i formuläret. Ladda vald spelare och kasta dina ändringar?',
    removeBlockedUseWithdraw:
      'Du kan inte ta bort en spelare som är inlottad i turneringen — använd "utgår från rond" istället.',
  },
  club: {
    enterName: 'Ange klubbnamn:',
  },
  pairingSystems: {
    berger: 'Berger',
    monrad: 'Monrad',
    nordicSchweizer: 'Nordisk Schweizer',
  },
  ratingChoices: {
    elo: 'ELO',
    rapidElo: 'Snabb-ELO',
    blitzElo: 'Blixt-ELO',
    rapidOrElo: 'Snabb-ELO annars ELO',
    blitzOrElo: 'Blixt-ELO annars ELO',
  },
} as const
